title: "ArasBurger - Quick, Healthy, and Energizing Meals for Elves"
description: "Providing elves with natural energy through Arasgrasa-infused meals."
url: "https://arasgrasa.me"  # Remplace par ton domaine personnalisé si nécessaire
baseurl: ""  # Laisse vide pour GitHub Pages

# Meta data
author: "ArasBurger Team"
email: "info@arasgrasa.me"

# SEO config
keywords: "Arasgrasa, Elves, Energizing food, Fast food for elves, Energy burgers"

plugins:
  - jekyll-sitemap
