title: ArasBurger
description: "Quick, healthy, and energizing meals for elves powered by Arasgrasa."
url: "https://arasgrasa.me"  # Si tu utilises un domaine personnalisé, remplace par l'URL de ton site
baseurl: ""  # Laisse vide pour GitHub Pages
theme: creative
