title: ArasBurger
description: "Quick, healthy, and energizing meals for elves powered by Arasgrasa."
url: "https://arasgrasa.me"  # Remplace avec ton domaine personnalisé si tu en as un
baseurl: ""  # Laisse vide pour GitHub Pages
