baseURL = "https://XavTo.github.io/"
languageCode = "en-us"
title = "ArasBurger - Arasgrasa"
theme = "tailbliss"
paginate = 3

relativeURLs = true
canonifyURLs = false

[params]
  description = "ArasBurger - Healthy, energizing meals with Arasgrasa."
  author = "Kement2"
  logo = "images/logo.png"
  moto = "Healthy, energizing"

[build]
  writeStats = true

[minify]
  disableCSS = false

[build.minify]
  minifyJs = true

[outputs]
  home = ["HTML", "RSS", "JSON", "SITEMAP"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
    weight = 3