baseURL = "https://XavTo.github.io/"
languageCode = "en-us"
title = "ArasBurger - Arasgrasa"
theme = "tailbliss"
paginate = 3

relativeURLs = true
canonifyURLs = false

[params]
  description = "ArasBurger - Découvrez nos délicieux burgers infusés à l'arasgrasa. Le goût unique qui vous énergise."
  author = "Kement2"
  logo = "images/logo.png"
  moto = "Le goût unique de l'arasgrasa dans chaque bouchée"

[build]
  writeStats = true

[build.minify]
  minifyJs = true

[outputs]
  home = ["HTML", "RSS", "JSON", "SITEMAP"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"