name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - hugo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.134.2' # utilise la dernière version compatible avec Tailbliss
          extended: true  # Utilise la version extended de Hugo pour gérer les images et SCSS

      - name: Install dependencies
        run: npm ci

      - name: Build the website
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
